# Generated by Django 2.1.5 on 2020-05-16 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarks.Bookmarks')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarks.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='customer',
            field=models.ManyToManyField(through='bookmarks.customer_bookmark', to='bookmarks.Customer'),
        ),
    ]
