# Generated by Django 2.1.5 on 2020-05-16 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_auto_20200516_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_bookmark',
            name='bookmark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark', to='bookmarks.Bookmarks'),
        ),
        migrations.AlterField(
            model_name='customer_bookmark',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='bookmarks.Customer'),
        ),
        migrations.AlterUniqueTogether(
            name='customer_bookmark',
            unique_together={('customer', 'bookmark')},
        ),
    ]
