# Generated by Django 2.1.5 on 2020-05-16 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0007_bookmarks_cust'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmarks',
            old_name='cust',
            new_name='customer',
        ),
    ]
